general.import = [ "dracula.toml" ]

[env]
TERM = "xterm-256color"

[window]
# opacity = 1
padding = { x = 10, y = 10 }

# [window]
opacity = 0.75

[colors.primary]
background = "#000000"

[font]
size = 10
