#!/usr/bin/env sh

# Check `bluetoothctl gatt.list-attributes` to find paths for `Battery Level`

MAC_ADDR=D9_E8_77_04_D2_4D
L_KB_PATH=service0010/char0011
R_KB_PATH=service0015/char0016
HCI=$(ls /sys/class/bluetooth/ | grep -o 'hci[0-9]*' | head -1)

L_KB_HEX=$(gdbus call --system --dest org.bluez --object-path /org/bluez/$HCI/dev_$MAC_ADDR/$L_KB_PATH --method org.bluez.GattCharacteristic1.ReadValue "{}"  | sed -E 's/.*0x([0-9a-fA-F]+).*/\1/');
R_KB_HEX=$(gdbus call --system --dest org.bluez --object-path /org/bluez/$HCI/dev_$MAC_ADDR/$R_KB_PATH --method org.bluez.GattCharacteristic1.ReadValue "{}"  | sed -E 's/.*0x([0-9a-fA-F]+).*/\1/');

echo " $((16#$L_KB_HEX))%|$((16#$R_KB_HEX))%"
