#!/bin/bash

tmux rename-window -t 0 'Nvim Config'
tmux send-keys -t 'Nvim Config' 'cd ~/.config/nvim' C-m
tmux send-keys -t 'Nvim Config' 'nvim .' C-m

tmux new-window -n 'Terminal'

tmux new-window -n 'Nvim 1'
tmux send-keys -t 'Nvim 1' 'nvim .' C-m

tmux new-window -n 'Nvim 2'
tmux send-keys -t 'Nvim 2' 'nvim .' C-m
