#!/bin/sh

chosen=$(printf "Power Off\nRestart\nHibernate" | rofi -dmenu -i)

case "$chosen" in
	"Power Off") poweroff ;;
	"Restart") reboot ;;
	"Hibernate") systemctl hibernate ;;
	*) exit 1 ;;
esac
