#!/usr/bin/env bash

NAME=$(ip -4 addr show | grep "^2: [0-9a-zA-Z]\+" -o | sed "s/2: //");
RESULT=$(ip -4 addr show | grep "$NAME" | grep -o "inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+" | sed "s/inet //");
if [[ $RESULT ]];
then
	echo "$UP_LABEL $RESULT";
else
	echo "$DOWN_LABEL Unavailable"
	echo "$DOWN_LABEL Unavailable"
  echo \#FF0000 # color
	exit
fi
