return {
	-- "adalessa/laravel.nvim",
	-- dependencies = {
	-- 	"kevinhwang91/promise-async",
	-- 	"nvim-telescope/telescope.nvim",
	-- 	"tpope/vim-dotenv",
	-- 	"MunifTanjim/nui.nvim",
	-- 	"nvimtools/none-ls.nvim",
	-- 	"nvim-neotest/nvim-nio",
	-- },
	-- cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" },
	-- keys = {
	-- 	{ "<leader>la", ":Laravel artisan<cr>" },
	-- 	{ "<leader>lr", ":Laravel routes<cr>" },
	-- 	{ "<leader>lm", ":Laravel related<cr>" },
	-- },
	-- event = { "VeryLazy" },
	-- config = true,
	-- cond = function()
	--   return vim.fn.filereadable("artisan") == 1
	-- 	  or vim.fn.filereadable("composer.json") == 1
	-- end,
}
